### ISSUE TITLE
installation requires to be run from a git repo that contains `spec_helper` file

### ISSUE THREAD

**Issue by mpugach** [matti/wdbomber#1]
```bash
➜  multi_project_repo git:(master) ✗ gem install wdbomber
Building native extensions. This could take a while...
fatal: not a git repository (or any of the parent directories): .git
/Users/mpugach/.rvm/rubies/ruby-2.5.1/bin/ruby -I/Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo'
'supervisor_cloud/gems/rspec-support-3.8.0/lib:/Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo'
'supervisor_cloud/gems/rspec-core-3.8.0/lib /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo'
'supervisor_cloud/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
sh: line 1: supervisor_cloud/extensions/x86_64-darwin-16/2.5.0/superbot-selenium-webdriver-1.0.1: No such file or directory
ERROR:  Error installing wdbomber:
	ERROR: Failed to build gem native extension.

    current directory: /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/superbot-selenium-webdriver-1.0.1
/Users/mpugach/.rvm/rubies/ruby-2.5.1/bin/ruby -rrubygems /Users/mpugach/.rvm/gems/ruby-2.5.1@global/gems/rake-12.3.0/exe/rake RUBYARCHDIR=/Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/extensions/x86_64-darwin-16/2.5.0/superbot-selenium-webdriver-1.0.1 RUBYLIBDIR=/Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/extensions/x86_64-darwin-16/2.5.0/superbot-selenium-webdriver-1.0.1
/Users/mpugach/.rvm/rubies/ruby-2.5.1/bin/ruby -I/Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo'
'supervisor_cloud/gems/rspec-support-3.8.0/lib:/Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo'
'supervisor_cloud/gems/rspec-core-3.8.0/lib /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo'
'supervisor_cloud/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading spec_helper.
Failure/Error: return gem_original_require(path)

LoadError:
  cannot load such file -- spec_helper
# /Users/mpugach/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
# /Users/mpugach/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in `load_file_handling_errors'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1519:in `block in requires='
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1519:in `each'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1519:in `requires='
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/configuration_options.rb:113:in `block in process_options_into'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/configuration_options.rb:112:in `each'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/configuration_options.rb:112:in `process_options_into'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/configuration_options.rb:22:in `configure'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:127:in `configure'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:97:in `setup'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:86:in `run'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/rspec-core-3.8.0/exe/rspec:4:in `<main>'
#
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.
No examples found.
No examples found.


Finished in 0.00031 seconds (files took 0.10748 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00031 seconds (files took 0.10748 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples


sh: line 2: supervisor_cloud/extensions/x86_64-darwin-16/2.5.0/superbot-selenium-webdriver-1.0.1: No such file or directory

rake failed, exit code 127

Gem files will remain installed in /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/gems/superbot-selenium-webdriver-1.0.1 for inspection.
Results logged to /Users/mpugach/.rvm/gems/ruby-2.5.1@multi_project_repo
supervisor_cloud/extensions/x86_64-darwin-16/2.5.0/superbot-selenium-webdriver-1.0.1/gem_make.out
```
```bash
➜  multi_project_repo git:(master) ✗ cd a_rails_sub_app
```
```bash
➜  a_rails_sub_app git:(master) ✗ gem install wdbomber
Fetching: archive-zip-0.11.0.gem (100%)
Successfully installed archive-zip-0.11.0
Fetching: chromedriver-helper-2.1.0.gem (100%)
Successfully installed chromedriver-helper-2.1.0
Fetching: selenium-webdriver-3.141.0.gem (100%)
Successfully installed selenium-webdriver-3.141.0
Fetching: superbot-selenium-webdriver-1.0.1.gem (100%)
Building native extensions. This could take a while...
Successfully installed superbot-selenium-webdriver-1.0.1
Fetching: wdbomber-0.1.3.gem (100%)
Successfully installed wdbomber-0.1.3
5 gems installed
```

**Comment by matti** [comment]
nope?

```
➜  ~ mkdir -p tmp/doesnotexist
➜  ~ cd tmp/doesnotexist
➜  doesnotexist $ gem install wdbomber
Successfully installed wdbomber-0.1.3
1 gem installed
```

**Comment by mpugach** [comment]
yep
